experiment_name: "informative_missingness"

data:
  test_size: 0.2 # proportion of data to be used for testing
  tabular:
    data_path: "../dataset/preprocessed_tabular/"
    window_size: 7 # intitial window size for tabular data
    feature_type: "numeric" # categorical, numeric
    aggregation_window_size: 12 # hours for aggregation 
    training_feature: "target" # target, gender, race, anchor_age
    age_threshold: 30 # age threshold for training feature
  temporal:
    data_path: "../dataset/preprocessed_temporal/"

model:
  model_type: "RandomForestClassifier"
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42
    class_weight: "balanced"
    min_samples_split: 2
    min_samples_leaf: 1
    # dropout_rate: 0.1
training:
  validation_split: 0.2
evaluation:
  metrics: ["accuracy", "f1_score", "precision", "recall"]
logging:
  log_level: "info" # options: debug, info, warning, error, critical
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
